version: "3.9"
services:
  async_downloader:
    build: .
    container_name: async_downloader
    ports: 
      - "8080:8080"
    volumes:
      - {REPLACE_ME}:/opt/app/photos
    environment:
      - LOGGING=False
      - DELAY=0
